### ISSUE TITLE
Where to find lib package?

### ISSUE THREAD

**Issue by AlexTan-b-z** [foocker/lsp#1]
Hello!
I find `from lib.solover.trainer import Trainer` in `train.py`.
But the project has no `lib` package.
Where to find lib package?

**Comment by foocker** [comment]
> Hello! I find `from lib.solover.trainer import Trainer` in `train.py`. But the project has no `lib` package. Where to find lib package?

the lib dir is the lib package, or you can try
```
import sys
sys.path.insert(0, os.path.dirname(__file__))
```
