### ISSUE TITLE
No module named 'standard_rasterize_cuda'

### ISSUE THREAD

**Issue by heiheiwangergou** [foocker/lsp#10]
File "/root/lihu/miniconda3/envs/get_lspdata/lib/python3.6/imp.py", line 297, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named 'standard_rasterize_cuda'
 
how to solve this problem  thanks

**Comment by zengxiang1** [comment]
改一下代码。用pytorch3d
