### ISSUE TITLE
how to get this mean_pts_3d_fixed_countour_nose_closemouth.npy file 

### ISSUE THREAD

**Issue by heiheiwangergou** [foocker/lsp#11]
when i run python train.py 

FileNotFoundError: [Errno 2] No such file or directory: '/root/lihu/lsp/otherlib/deca/hk_fake_8_14_LSP/label/mean_pts_3d_fixed_countour_nose_closemouth.npy'

**Comment by foocker** [comment]
> when i run python train.py
> 
> FileNotFoundError: [Errno 2] No such file or directory: '/root/lihu/lsp/otherlib/deca/hk_fake_8_14_LSP/label/mean_pts_3d_fixed_countour_nose_closemouth.npy'

you must prepare the training and testing data use your own video. follow the data prepare function.

**Comment by heiheiwangergou** [comment]
> > when i run python train.py
> > FileNotFoundError: [Errno 2] No such file or directory: '/root/lihu/lsp/otherlib/deca/hk_fake_8_14_LSP/label/mean_pts_3d_fixed_countour_nose_closemouth.npy'
> 
> you must prepare the training and testing data use your own video. follow the data prepare function.

python video_preprocess.py
1. video preprocess
    1. change fps to 60
    2. crop video to (512, 512)
    3. translate video to images
    4. extract audio from croped video
    5. merge audio, images, or video to new video.
2. translated imgs
    1. using deca to extract useful information 
    2. cd otherlib/deca
    sh run.sh

I have do it ,but did not creat this npy file
