### ISSUE TITLE
How to use deca to extract useful information?

### ISSUE THREAD

**Issue by Arthurzhangsheng** [foocker/lsp#13]
folloing the readme,  I finished the steps below:
1. video preprocess
    1. change fps to 60
    2. crop video to (512, 512)
    3. translate video to images
    4. extract audio from croped video
    5. merge audio, images, or video to new video.

but the next step "1. using deca to extract useful information " confused me a lot
how to use deca to extract useful information? 
which  .py script is need to do this job?
Could someone help me?

**Comment by foocker** [comment]
> 

use the new version.
