### ISSUE TITLE
No such file or directory:mean_pts_3d_fixed_countour_nose_closemouth.npy'

### ISSUE THREAD

**Issue by heiheiwangergou** [foocker/lsp#15]
after bash run.sh 
label file have  these 3d_fit_data_224.npz  3d_fit_data.npz  camera_extrinsics.npy  cams.npy  img_meta.npy  landmarks2d_original.npy  mean_pts_3d.npy  tforms.npy  file 
then i  python train.py 

  File "train.py", line 25, in <module>
    main(cfg)
  File "train.py", line 15, in main
    trainer.fit()
  File "/workspace/raid02/edu/LIHU/lsp/lib/solover/trainer.py", line 280, in fit
    self.prepra_data()
  File "/workspace/raid02/edu/LIHU/lsp/lib/solover/trainer.py", line 275, in prepra_data
    self.train_dataset = build_dataset(self.cfg)
  File "/workspace/raid02/edu/LIHU/lsp/lib/datasets/build_datasets.py", line 7, in build_dataset
    dataset = AudioVisualDataset(cfg)
  File "/workspace/raid02/edu/LIHU/lsp/lib/datasets/audiovisual_dataset.py", line 68, in __init__
    self.pts3d_mean = np.load(os.path.join(self.data3d_label_dir, 'mean_pts_3d_fixed_countour_nose_closemouth.npy'))
  File "/root/lihu/miniconda3/envs/deca/lib/python3.7/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/root/lihu/lsp/data/hk_fake_8_14/label/mean_pts_3d_fixed_countour_nose_closemouth.npy'

大佬  can you tell me  how to get this file

**Comment by heiheiwangergou** [comment]
[noise_resilient_3dtface](https://github.com/eeskimez/noise_resilient_3dtface)    
 this git can create mean_pts_3d_fixed_countour_nose_closemouth.npy  ?

**Comment by foocker** [comment]
> [noise_resilient_3dtface](https://github.com/eeskimez/noise_resilient_3dtface) this git can create mean_pts_3d_fixed_countour_nose_closemouth.npy ?

this file's name, you can change. the basic need files you can reference the original lsp git.  xx_fixed_countour_nose_closemouth is only from my handle function. you can choose the other function(in the script file).

**Comment by heiheiwangergou** [comment]
> > [noise_resilient_3dtface](https://github.com/eeskimez/noise_resilient_3dtface) this git can create mean_pts_3d_fixed_countour_nose_closemouth.npy ?
> 
> this file's name, you can change. the basic need files you can reference the original lsp git. xx_fixed_countour_nose_closemouth is only from my handle function. you can choose the other function(in the script file).


Boss, can you elaborate on what to do

**Comment by heiheiwangergou** [comment]
> > [noise_resilient_3dtface](https://github.com/eeskimez/noise_resilient_3dtface) this git can create mean_pts_3d_fixed_countour_nose_closemouth.npy ?
> 
> this file's name, you can change. the basic need files you can reference the original lsp git. xx_fixed_countour_nose_closemouth is only from my handle function. you can choose the other function(in the script file).


Can you elaborate on how to generate this npy file，thank you

**Comment by foocker** [comment]
> 

answer is in the giving code. try try. the basic trainning label, reference original repo.

**Comment by foocker** [comment]
> > > > [noise_resilient_3dtface](https://github.com/eeskimez/noise_resilient_3dtface) this git can create mean_pts_3d_fixed_countour_nose_closemouth.npy ?
> > > 
> > > 
> > > this file's name, you can change. the basic need files you can reference the original lsp git. xx_fixed_countour_nose_closemouth is only from my handle function. you can choose the other function(in the script file).
> > 
> > 
> > Can you elaborate on how to generate this npy file，thank you
> 
> > > [noise_resilient_3dtface](https://github.com/eeskimez/noise_resilient_3dtface) this git can create mean_pts_3d_fixed_countour_nose_closemouth.npy ?
> > 
> > 
> > this file's name, you can change. the basic need files you can reference the original lsp git. xx_fixed_countour_nose_closemouth is only from my handle function. you can choose the other function(in the script file).
> 
> after python train.py FileNotFoundError: [Errno 2] No such file or directory: '/root/lihu/lsp/data/hk_fake_8_14/label/mean_pts_3d_fixed_countour_nose_closemouth.npy' how can i slove this problem 大佬 thank you

![图片](https://user-images.githubusercontent.com/21965361/213068001-349fd142-c617-4f6d-9fe0-800243fc747e.png)

**Comment by matlab2017** [comment]
> > > > [noise_resilient_3dtface](https://github.com/eeskimez/noise_resilient_3dtface) this git can create mean_pts_3d_fixed_countour_nose_closemouth.npy ?
> > > 
> > > 
> > > this file's name, you can change. the basic need files you can reference the original lsp git. xx_fixed_countour_nose_closemouth is only from my handle function. you can choose the other function(in the script file).
> > 
> > 
> > Can you elaborate on how to generate this npy file，thank you
> 
> > > [noise_resilient_3dtface](https://github.com/eeskimez/noise_resilient_3dtface) this git can create mean_pts_3d_fixed_countour_nose_closemouth.npy ?
> > 
> > 
> > this file's name, you can change. the basic need files you can reference the original lsp git. xx_fixed_countour_nose_closemouth is only from my handle function. you can choose the other function(in the script file).
> 
> after python train.py FileNotFoundError: [Errno 2] No such file or directory: '/root/lihu/lsp/data/hk_fake_8_14/label/mean_pts_3d_fixed_countour_nose_closemouth.npy' how can i slove this problem 大佬 thank you

Did you successfully run the code？
