### ISSUE TITLE
The predicted images of landmarks are completely black.

### ISSUE THREAD

**Issue by matlab2017** [foocker/lsp#16]
大佬 我按照readme的过程训练完三个模型后为啥landmarks生成的图像是全黑的  是还有其他额外的步骤还是需要调整代码

**Comment by foocker** [comment]
> 

more infomation?

**Comment by foocker** [comment]
> 大佬 我按照readme的过程训练完三个模型后为啥landmarks生成的图像是全黑的 是还有其他额外的步骤还是需要调整代码

more infomation?

**Comment by foocker** [comment]
> 大佬 我按照readme的过程训练完三个模型后为啥landmarks生成的图像是全黑的 是还有其他额外的步骤还是需要调整代码

**Comment by matlab2017** [comment]
In thee demo.py, is the function def ndc2img(landmarks3d) necessary? When run this step, the range of values obtained is well beyond 512.  After commenting out, the result looks normal.

**Comment by foocker** [comment]
> 
there are two ways, as you can see in the code, some time , you can choose x, some time you must choose xx.
