### ISSUE TITLE
可以说说tracked3D_normalized_pts_fix_contour.npy这个文件是怎么来的 么

### ISSUE THREAD

**Issue by zengxiang1** [foocker/lsp#19]

**Comment by foocker** [comment]
> _No description provided._

人脸重建算法得到的3d landmarks, 根据一个标准人脸做的对齐。比如仿射变换，求得每一帧的3dlamdmarks和第一帧的变换矩阵，然后逆变换后面的每一帧。 
这里人脸重建可以替换，具体对齐方式也可以替换。我在参考论文中，提到过一篇英伟达的论文，只是在我的基础上，做了鼻子上的一些限制，论文有张图，很容易实现。 
上面我说的实现方式，在代码里都有。 只是实验太多了，现在没做这个，就没clean了。
