### ISSUE TITLE
可以帮我看下么， 我运行完demo之后得到这么一个结果

### ISSUE THREAD

**Issue by zengxiang1** [foocker/lsp#20]
<img width="505" alt="image" src="https://user-images.githubusercontent.com/16497064/232259963-444371a3-4d83-4279-9e7d-bd29276ee04f.png">

**Comment by foocker** [comment]
> <img alt="image" width="505" src="https://user-images.githubusercontent.com/16497064/232259963-444371a3-4d83-4279-9e7d-bd29276ee04f.png">

代码里有生成器的测试，你先测试下生成器的效果，landmarks可视化，也看看。

**Comment by 91xiaoyang** [comment]
> > <img alt="图像" width="505" src="https://user-images.githubusercontent.com/16497064/232259963-444371a3-4d83-4279-9e7d-bd29276ee04f.png">
> 
> 代码里有生成器的测试，你先测试下生成器的效果，landmarks可视觉化，也看看。[test_scripts](https://github.com/foocker/lsp/tree/main/test_scripts) /test_infer.py

landmarks3d_fixed_countour_nose.npy这个文件是在哪里生成的呢，我数据处理后并没有生成它
