### ISSUE TITLE
Thank you to the author. How should I start my training? For example, how long do I need to prepare videos and what code I need to run to process my data to obtain something similar to mean_ pts_ 3d_ fixed_ countour_ nose_ What about closemouth. npy '?

### ISSUE THREAD

**Issue by 91xiaoyang** [foocker/lsp#21]
File "D:\Preject\DS_Project\lsp-main\lib\datasets\audiovisual_dataset.py", line 68, in __init__
    self.pts3d_mean = np.load(os.path.join(self.data3d_label_dir, 'mean_pts_3d_fixed_countour_nose_closemouth.npy'))
  File "C:\Users\Administrator\.conda\envs\LSP\lib\site-packages\numpy\lib\npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/home/yourname/lsp/data/hk_fake_8_14\\label\\mean_pts_3d_fixed_countour_nose_closemouth.npy'

**Comment by foocker** [comment]
> File "D:\Preject\DS_Project\lsp-main\lib\datasets\audiovisual_dataset.py", line 68, in **init** self.pts3d_mean = np.load(os.path.join(self.data3d_label_dir, 'mean_pts_3d_fixed_countour_nose_closemouth.npy')) File "C:\Users\Administrator.conda\envs\LSP\lib\site-packages\numpy\lib\npyio.py", line 416, in load fid = stack.enter_context(open(os_fspath(file), "rb")) FileNotFoundError: [Errno 2] No such file or directory: '/home/yourname/lsp/data/hk_fake_8_14\label\mean_pts_3d_fixed_countour_nose_closemouth.npy'

yourname means, replace it by yourself path. 5 minutes video. data prepar scripts all comes from handle_all function in preprocess.py.
