### ISSUE TITLE
how can i  get /data/lsp-main/otherlib/deca/data/head_template.obj

### ISSUE THREAD

**Issue by angelandy** [foocker/lsp#24]
hi 
i get the error like this

  warnings.warn(
/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and will be removed in 0.15. The current behavior is equivalent to passing `weights=None`.
  warnings.warn(msg)
creating the FLAME Decoder
please check model path: /data/lsp-main/otherlib/deca/data/deca_model.tar
Traceback (most recent call last):
  File "/data/lsp-main/otherlib/deca/demos/lsp_data_generator.py", line 699, in <module>
    main(args)
  File "/data/lsp-main/otherlib/deca/demos/lsp_data_generator.py", line 431, in main
    deca = DECA(config=deca_cfg, device=device)
  File "/data/lsp-main/otherlib/deca/decalib/deca.py", line 50, in __init__
    self._setup_renderer(self.cfg.model)
  File "/data/lsp-main/otherlib/deca/decalib/deca.py", line 54, in _setup_renderer
    self.render = SRenderY(self.image_size, obj_filename=model_cfg.topology_path, uv_size=model_cfg.uv_size,\
  File "/data/lsp-main/otherlib/deca/decalib/utils/renderer.py", line 187, in __init__
    verts, uvcoords, faces, uvfaces = load_obj(obj_filename)
  File "/data/lsp-main/otherlib/deca/decalib/utils/util.py", line 162, in load_obj
    with open(obj_filename, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/data/lsp-main/otherlib/deca/data/head_template.obj'

**Comment by angelandy** [comment]
@foocker can you help?

**Comment by foocker** [comment]
> @foocker can you help?

look the readme. you need download some file from the deca readme.  
[head_template.zip](https://github.com/foocker/lsp/files/12571560/head_template.zip)

**Comment by angelandy** [comment]
so, .obj is create by deca 。
how about uv_face_eye_mask.png and uv_face_mask.png

**Comment by foocker** [comment]
> so, .obj is create by deca 。 how about uv_face_eye_mask.png and uv_face_mask.png

should also comes form deca.  see deca sub module in lsp.
![uv_face_mask](https://github.com/foocker/lsp/assets/21965361/aefcdcd8-77cc-4904-b30c-14973e16b8ae)
![mean_texture](https://github.com/foocker/lsp/assets/21965361/5ee3f12e-b7bb-4ef2-a179-ffe10f84c3f0)
![uv_face_eye_mask](https://github.com/foocker/lsp/assets/21965361/6c7b28b5-2736-4233-87aa-85201524ccab)
