### ISSUE TITLE
我很想尝试跑通代码训练出和您一样好的效果, 但我遇到一些问题, 可以帮助我吗

### ISSUE THREAD

**Issue by Hujiazeng** [foocker/lsp#25]
感谢作者的奉献, 非常伟大。

我跟随指引训练了模型, 调节yaml中的参数, 得到了以下的结果

https://github.com/foocker/lsp/assets/76672298/b4dffeab-9cd3-42f9-8cd1-4838f3331f51

是我在哪个步骤做错了什么, 您有什么好的建议吗

**Comment by Hujiazeng** [comment]
https://github.com/foocker/lsp/assets/76672298/5d152644-d6ab-473f-b0bd-0530b8063bb0

**Comment by foocker** [comment]
> infer_result_audio.mp4
你这个应该是audio2landmark都没做好。你先可视化一下它，我gallary中那样，这个最关键。
整个pipeline的每个步骤都可以可视化检测，首先audio2landmarks要好(稳定，形变小)，其次，生成模型要好(你可以用训练的landmark去测试生成模型的效果)，然后二者结合，audio2pose我没做好，当前git的代码，不能做到我gallary中的效果，对齐和audio2headpose都要改进，不在网络上的改进，而是处理上的优化。

**Comment by lion-ops** [comment]
看到您那边跑通了，请教下，landmarks3d_fixed_countour_nose.npy，这个文件是怎么来的呢，我缺少这个文件，模型训练不起来
