### ISSUE TITLE
请教几个问题

### ISSUE THREAD

**Issue by NaMoCv** [foocker/lsp#27]
1、模型支持什么尺寸的视频呢？是任何尺寸都可以吗？
2、random 4 img from imgs有什么作用呢？

**Comment by foocker** [comment]
> 1、模型支持什么尺寸的视频呢？是任何尺寸都可以吗？ 2、random 4 img from imgs有什么作用呢？

1. 忘了，512*512的吧。看了下G的代码，是可以不同尺度的，其他部分，你得看下了。
2. 被训练人的图片作为导引(条件)，生成的效果更好。
