### ISSUE TITLE
g_sample, label

### ISSUE THREAD

**Issue by wnqw** [foocker/lsp#29]
In the data folder:
1. what images should I put inside g_sample? 
2. What specific files should I put inside 'label' folder? 
(should I put the files that are left out from data folder in original LSP repo?: 3d_fit_data.npz                 shoulder_points3D.npy
camera_intrinsic.npy            tracked2D_normalized_pts_fix_contour.npy
change_paras.npz                tracked3D_normalized_pts_fix_contour_bk.npy
mean_pts3d.npy                  tracked3D_normalized_pts_fix_contour.npy
normalized_shoulder_points.npy)

**Comment by foocker** [comment]
> In the data folder:
> 
>     1. what images should I put inside g_sample?
> 
>     2. What specific files should I put inside 'label' folder?
>        (should I put the files that are left out from data folder in original LSP repo?: 3d_fit_data.npz                 shoulder_points3D.npy
>        camera_intrinsic.npy            tracked2D_normalized_pts_fix_contour.npy
>        change_paras.npz                tracked3D_normalized_pts_fix_contour_bk.npy
>        mean_pts3d.npy                  tracked3D_normalized_pts_fix_contour.npy
>        normalized_shoulder_points.npy)

g_sample is just for test the submodel of generator is woking or not. label as you want to do. keep the mini need is ok.
