### ISSUE TITLE
Help running video_preprocess

### ISSUE THREAD

**Issue by andresPenagos00** [foocker/lsp#4]
Hi foocker, thanks for your repository, can you help me, I am running step 1 video_preprocess.py
1.video preprocessing
     1. change fps to 60
     2. crop video to (512, 512)
     3. translate video to images
     4. extract audio from cropped video
     5. Merge audio, images, or video to new video.

but in the video_preprocess.py file

`if __name__ == "__main__":
    # vp = './hk_fake_38_half.mp4'
    # vp = './croped_hk_fake_38_half_60fps.mp4'
    # vp = './data/hk_fake_38/test_mouth_new.mp4'
    # vp = './data/hk_fake_38/original_landmarks.mp4'
    # vp = './data/hk_fake_38/landmarks3d_fixed_countour_nose.mp4'
    # vp = './data/hk_fake_38/test_all_train_add_headpose.mp4'
    croped_vp = './data/hk_fake_8_14/croped_half_hk_fake_8_14_60fps.mp4'
    dst_dir = '/home/yourname/DECA/DECA/hk_fake_8_14_imgs'
    
    # wav = './data/hk_fake_38/video_audio/audio.wav'
    # wav = './data/hk_fake_38/video_audio/Mayun.wav'
    
    # img2video('./imgs', './video/kanghui_5_10.avi')
    # kp = parser_json('./kanghui_5_1.json')
    # kp = parser_json('./kanghui_5_60fps_crop_512_1.json')
    # print(kp)
    # lucas_kanade_method_imgs('./kanghui_imgs_512', kp, save_kp_dir='./kp_save_kh')
    # check_should2d('./kp_save_kh/shoulder_2D.npy', './kanghui_imgs_512')
    # x = np.load('./kp_save_girl/shoulder_2D.npy')
    # print(x.shape)

    fan = FAN()
    # croped_vp = fan.crop_video_letterbox(vp, face_head_scale=1.5)
    # fan.video_read_message(croped_vp)
    # result_file = fan.change_vd_fps(croped_vp)
    # fan.video_read_message(result_file)
    # fan.video_read_message(croped_vp)
    fan.extract_imgs(croped_vp, dst_dir)
    
    # fan.extract_audio(croped_vp)
    # fan.merge_audio_video(vp, wav)
    # merge_audio_video('noaudio_croped_hk_fake_38_half_60fps.mp4', 'croped_hk_fake_38_half_60fps.wav')`

It's all commented, can you help me with what step I should follow, thanks for your help.

**Comment by foocker** [comment]
> Hi foocker, thanks for your repository, can you help me, I am running step 1 video_preprocess.py 1.video preprocessing 1. change fps to 60 2. crop video to (512, 512) 3. translate video to images 4. extract audio from cropped video 5. Merge audio, images, or video to new video.
> 
> but in the video_preprocess.py file
> 
> `if **name** == "**main**": # vp = './hk_fake_38_half.mp4' # vp = './croped_hk_fake_38_half_60fps.mp4' # vp = './data/hk_fake_38/test_mouth_new.mp4' # vp = './data/hk_fake_38/original_landmarks.mp4' # vp = './data/hk_fake_38/landmarks3d_fixed_countour_nose.mp4' # vp = './data/hk_fake_38/test_all_train_add_headpose.mp4' croped_vp = './data/hk_fake_8_14/croped_half_hk_fake_8_14_60fps.mp4' dst_dir = '/home/yourname/DECA/DECA/hk_fake_8_14_imgs'
> 
> ```
> # wav = './data/hk_fake_38/video_audio/audio.wav'
> # wav = './data/hk_fake_38/video_audio/Mayun.wav'
> 
> # img2video('./imgs', './video/kanghui_5_10.avi')
> # kp = parser_json('./kanghui_5_1.json')
> # kp = parser_json('./kanghui_5_60fps_crop_512_1.json')
> # print(kp)
> # lucas_kanade_method_imgs('./kanghui_imgs_512', kp, save_kp_dir='./kp_save_kh')
> # check_should2d('./kp_save_kh/shoulder_2D.npy', './kanghui_imgs_512')
> # x = np.load('./kp_save_girl/shoulder_2D.npy')
> # print(x.shape)
> 
> fan = FAN()
> # croped_vp = fan.crop_video_letterbox(vp, face_head_scale=1.5)
> # fan.video_read_message(croped_vp)
> # result_file = fan.change_vd_fps(croped_vp)
> # fan.video_read_message(result_file)
> # fan.video_read_message(croped_vp)
> fan.extract_imgs(croped_vp, dst_dir)
> 
> # fan.extract_audio(croped_vp)
> # fan.merge_audio_video(vp, wav)
> # merge_audio_video('noaudio_croped_hk_fake_38_half_60fps.mp4', 'croped_hk_fake_38_half_60fps.wav')`
> ```
> 
> It's all commented, can you help me with what step I should follow, thanks for your help.

sorry, i open gayhub right now, maybe you can try  call the function of  video_preprocess(self), which contain the all step.
