### ISSUE TITLE
Loss of Audio2Feature

### ISSUE THREAD

**Issue by JJJJerry** [foocker/lsp#5]
when I train the model of Audio2Feature, the loss is very large,it reaches 1000 ,Is this normal?

**Comment by foocker** [comment]
> when I train the model of Audio2Feature, the loss is very large,it reaches 1000 ,Is this normal?

soory, i have forget this...

**Comment by zengxiang1** [comment]
> when I train the model of Audio2Feature, the loss is very large,it reaches 1000 ,Is this normal?

unnormal,   i ran it  from 1000 step to 24

**Comment by zengxiang1** [comment]
> > > when I train the model of Audio2Feature, the loss is very large,it reaches 1000 ,Is this normal?
> > 
> > 
> > unnormal, i ran it from 1000 step to 24
> 
> if inference result is good, it is right,or not. i have no time for training it again. in my memery, it right.

can you supply original data or where i can get it ,  i cant get the file landmarks3d_fixed_countour_nose.npy

**Comment by VishalAnton20** [comment]
can u share the google drive for Audio2Feature_196.tar'
