### ISSUE TITLE
No such file or directory: '/lsp/otherlib/deca/data/generic_model.pkl

### ISSUE THREAD

**Issue by artemis1919** [foocker/lsp#6]
The error occurs when I run `sh run.sh`

`FileNotFoundError: [Errno 2] No such file or directory: '/content/lsp/otherlib/deca/data/generic_model.pkl'`

What is the process of creating the generic_model.pkl?

Thanks a lot

**Comment by foocker** [comment]
> The error occurs when I run `sh run.sh`
> 
> `FileNotFoundError: [Errno 2] No such file or directory: '/content/lsp/otherlib/deca/data/generic_model.pkl'`
> 
> What is the process of creating the generic_model.pkl?
> 
> Thanks a lot

maybe you will download from ![smpl](https://smpl.is.tue.mpg.de/)

**Comment by pegahsalehi** [comment]
I appreciate your prompt response.

After downloading the required files and reruning, only `camera_extrinsics.npy` was created in `./otherlib/deca/hk_fake_8_14_LSP/label/`!!!

And as it is clear here, the process is not applied to all images (only 200 images!). Could you please tell me why this is happening?
```
['./hk_fake_8_14_imgs/1.png', './hk_fake_8_14_imgs/2.png', './hk_fake_8_14_imgs/3.png', './hk_fake_8_14_imgs/4.png', './hk_fake_8_14_imgs/5.png', './hk_fake_8_14_imgs/6.png', './hk_fake_8_14_imgs/7.png', './hk_fake_8_14_imgs/8.png', './hk_fake_8_14_imgs/9.png', './hk_fake_8_14_imgs/10.png']
creating the FLAME Decoder
trained model found. load /content/lsp/otherlib/deca/data/deca_model.tar
  1% **200/17986** [01:02<1:32:35,  3.20it/s]
```

**Comment by tylersky1993** [comment]
> > The error occurs when I run `sh run.sh`
> > `FileNotFoundError: [Errno 2] No such file or directory: '/content/lsp/otherlib/deca/data/generic_model.pkl'`
> > What is the process of creating the generic_model.pkl?
> > Thanks a lot
> 
> maybe you can download from ![smpl](https://camo.githubusercontent.com/e65519adde77be64e46a3172199cf8d99c2bc4e2d313bf4e25aa7c57f97a5ddb/68747470733a2f2f736d706c2e69732e7475652e6d70672e64652f)

I appreciate your prompt response.

After downloading the required files and reruning, only `camera_extrinsics.npy` was created in `./otherlib/deca/hk_fake_8_14_LSP/label/`!!!

And as it is clear here, the process is not applied to all images (only 200 images!). Could you please tell me why this is happening?
```
['./hk_fake_8_14_imgs/1.png', './hk_fake_8_14_imgs/2.png', './hk_fake_8_14_imgs/3.png', './hk_fake_8_14_imgs/4.png', './hk_fake_8_14_imgs/5.png', './hk_fake_8_14_imgs/6.png', './hk_fake_8_14_imgs/7.png', './hk_fake_8_14_imgs/8.png', './hk_fake_8_14_imgs/9.png', './hk_fake_8_14_imgs/10.png']
creating the FLAME Decoder
trained model found. load /content/lsp/otherlib/deca/data/deca_model.tar
  1% 200/17986 [01:02<1:32:35,  3.20it/s]
```
