### ISSUE TITLE
The order of running

### ISSUE THREAD

**Issue by artemis1919** [foocker/lsp#7]
Hi foocker, Thank you for the repository!

If possible, we would greatly appreciate it if you could let us know their order so that we can prepare the required training files. I'm a bit confused.

**Comment by foocker** [comment]
> 
in readme:
0. pyhton video_preprocess.py/video_preprocess
1. prepare data (deca or other 3d face reconstruct alg), deca in otherlib  demos/lsp_data_generator.py or run.sh
2. python train.py
2.1 change confile, task:Audio2Feature->Audio2Headpose(not good)->Feature2Face. audio2landmark is audio, generator is face, 
2.2 train time_frame_length is 240, test is 1. all choice you can konw in the config file.

**Comment by pegahsalehi** [comment]
Thank you for your response.

Why should we do these two steps?!

**extract audio from croped video
merge audio, images, or video to new video.**

**Comment by tylersky1993** [comment]
> > 
> 
> in readme: 0. pyhton video_preprocess.py/video_preprocess
> 
> 1. prepare data (deca or other 3d face reconstruct alg), deca in otherlib  demos/lsp_data_generator.py or run.sh
> 2. python train.py
>    2.1 change confile, task:Audio2Feature->Audio2Headpose(not good)->Feature2Face. audio2landmark is audio, generator is face,
>    2.2 train time_frame_length is 240, test is 1. all choice you can konw in the config file.

Thank you for your response.

Why should we do these two steps?!

extract audio from croped video
merge audio, images, or video to new video.

**Comment by Arthurzhangsheng** [comment]
> > > 
> > 
> > 
> > in readme: 0. pyhton video_preprocess.py/video_preprocess
> > 
> > 1. prepare data (deca or other 3d face reconstruct alg), deca in otherlib  demos/lsp_data_generator.py or run.sh
> > 2. python train.py
> >    2.1 change confile, task:Audio2Feature->Audio2Headpose(not good)->Feature2Face. audio2landmark is audio, generator is face,
> >    2.2 train time_frame_length is 240, test is 1. all choice you can konw in the config file.
> 
> Thank you for your response.
> 
> Why should we do these two steps?!
> 
> extract audio from croped video merge audio, images, or video to new video.

I have the same question. I can't understand the purpose of this step. I feel it is unnecessary
