### ISSUE TITLE
how to train my own person and get zhe data

### ISSUE THREAD

**Issue by heiheiwangergou** [foocker/lsp#8]
data
-- video_name
  -- APC
    --xx_APC_feature_xxx.npy
  --checkpoints
  --imgs
  --candidates
  --g_sample
  --label
    --3d_fit_data.npz
    --mean_pts_3d.npy
    --...
  --video_audio
these npy data how to get

**Comment by foocker** [comment]
> data -- video_name -- APC --xx_APC_feature_xxx.npy --checkpoints --imgs --candidates --g_sample --label --3d_fit_data.npz --mean_pts_3d.npy --... --video_audio these npy data how to get

in readme: python video_preprocess.py, 1 and 2.
